#!/usr/bin/env python3

import argparse
import subprocess
import os

print("Indexing...")

parser = argparse.ArgumentParser()
parser.add_argument("--collections", nargs="+", type=str, required=True, help="the collection names")

args, unknown = parser.parse_known_args()

for name in args.collections:
    
    #create a folder for this collection index
    os.mkdir("/work/indexes/{}".format(name), 777)
    
    subprocess.run("""
        /work/terrier-project-5.1/bin/trec_setup.sh 
        /input/collections/{0}""".format(name).split())
    
    subprocess.run("""
        /work/{0}/terrier-project-5.1/bin/terrier batchindexing -p 
        -I /work/indexes/{0}""".format(name).split())
