#!/usr/bin/env python3

import argparse
import subprocess
import os
import json

print("Indexing...")

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="json with arguments")

args, unknown = parser.parse_known_args()
if not os.path.isdir("/work/indexes"):
    os.mkdir("/work/indexes/", 777)


index_options = {
        "robust04" : "-Dterrier.mvn.coords=org.apache.commons:commons-compress:1.18 -Dfiles.mappings=Z:org.apache.commons.compress.compressors.z.ZCompressorInputStream:null -Dfiles.mappings=z:org.apache.commons.compress.compressors.z.ZCompressorInputStream:null" 
        }

for collection in args.json["collections"]:
    name, path = collection['name'], collection['path']
    params = index_options[name]
    
    subprocess.run("""
        /work/terrier-core/bin/trec_setup.sh 
        {0}""".format(path).split())
    
    subprocess.run("""
        /work/terrier-core/bin/terrier batchindexing
        -I /work/indexes/{0} {1}""".format(name, params).split())
