#!/usr/bin/env python3

import subprocess
import os

print("Initializing...")

#Download terrier from git and change commit version
subprocess.run("git clone https://github.com/terrier-org/terrier-core".split())
curr_dir = os.getcwd()
os.chdir("{}/terrier-core".format(curr_dir))

#install using mvn
subprocess.run("mvn -DskipTests -Dmaven.javadoc.skip=true clean install".split())
