#!/usr/bin/env python3

import subprocess

print("Initializing...")

#Download terrier, bypass "I Agree form"
import requests

headers = {
    'Proxy-Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Referer': 'http://terrier.org/download/agree.shtml?terrier-project-5.1-bin.tar',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7',
}

response = requests.get('http://terrier.org/download/files/terrier-project-5.1-bin.tar', headers=headers)

#untar to work directory
subprocess.run("tar -xvf terrier-project-5.1.bin.tar -C /work")

